- tests/simpleFramerISD.json
fixes #63 
Note that this is using the keywords from the Framer model we have, not keywords from the JSON schema (yet).
> Add simple framer ISD for tests

- tests/data/simpleFramerISD.json
Omega, phi and kappa were updated to 0, -Pi/2 and Pi respectively.
> updated isd to have correct rotation

- src/UsgsAstroFrameSensorModel.cpp
- tests/FrameCameraTests.cpp
> Test camera model

- include/usgscsm/UsgsAstroFramePlugin.h
- src/UsgsAstroFramePlugin.cpp
- src/UsgsAstroFrameSensorModel.cpp
- tests/FrameCameraTests.cpp
- tests/TestyMcTestFace.cpp
This includes the updates to `UsgsAstroFramePlugin` to switch from expecting the SET to parse a json ISD into a `csm::Isd` object that will be passed to this plugin to expecting the SET to construct a `csm::Isd('image file name')` to pass to the plugin. Now the plugin parses the json isd. It looks for a json isd file named 'filename.json' next to the provided image filename. This should fix #110 
The existing tests needed to be updated for this change. 
Now, `canModelBeConstructedFromISD` works on both 'filename only' `csm::Isd` objects and ones that have already been populated with values from the json isd file. 
I added a helper function I called `csm::Isd loadImageSupportData(const csm::Isd&) const` which takes a 'filename only' `csm::Isd` and creates and returns a new Isd populated …
> UsgsAstroFramePlugin refactor, part one

- src/UsgsAstroFramePlugin.cpp
- tests/FramePluginTests.cpp
This should fix #133 it will need to be built on windows to test for sure first.
> Fixed canModelBeConstructedFromISD throwing an exception when the metadata file doesn't exist.

- CMakeLists.txt
This PR is trying to make GTest fully optional to fix build issues on the conda-forge feedstock of CSM where GTest is not being installed and the GTest repo is not being cloned.
> Makes GTest fully optional

- src/UsgsAstroLsSensorModel.cpp
This error shouldn't be in here. The desired precision should be checking for this type of thing.
> Removed ground to image 10m error

- CMakeLists.txt
So, I did not isolate GTest enough. I just tested this on my Mac and:
```
TEST END: /Users/jlaura/miniconda3/conda-bld/osx-64/usgscsm-1.1.1-0.tar.bz2
Renaming work directory,  /<me>/miniconda3/conda-bld/usgscsm_1551115360642/work  to  /<me>/miniconda3/conda-bld/usgscsm_1551115360642/work_moved_usgscsm-1.1.1-0_osx-64_main_build_loop
anaconda upload /Users/jlaura/miniconda3/conda-bld/osx-64/usgscsm-1.1.1-0.tar.bz2
anaconda_upload is not set.  Not uploading wheels: []
```
> Further isolates gtest

- src/UsgsAstroLsSensorModel.cpp
It looks like reading off the end of the array was causing intermittent inaccuracies when interpolating the position and velocity.
Fixes #199 I ran the inversion test a 1000 times before and got failures. After the fix, no more failures!
> Fixed reading junk data, also cleaned up groundToImage

- include/usgscsm/UsgsAstroFrameSensorModel.h
- include/usgscsm/Utilities.h
- src/UsgsAstroFrameSensorModel.cpp
- src/UsgsAstroLsSensorModel.cpp
- src/Utilities.cpp
- tests/FrameCameraTests.cpp
- tests/UtilitiesTests.cpp
- tests/data/simpleFramerISD.json
Fixes #220 
- Changed the focal plane coordinate computation to just use 2 doubles instead of a tuple so that is better matches the rest of the utility functions.
- Removed the unused principal point from the framer.
- Added a utility function to convert a focal plane coordinate into a pixel. I didn't modify the line scanner to use this because it can't convert all the way to an image line. I'm also not sure how to incorporate line summing in the line scanner because it assumes 1 by X pixel ccds instead of full push broom sensors.
- Added more tests for utilities and the framer
> Added pixel summing in framer

- include/usgscsm/UsgsAstroFrameSensorModel.h
- src/UsgsAstroFrameSensorModel.cpp
- tests/Fixtures.h
- tests/FrameCameraTests.cpp
Once logging is in the line scan, we should do this for the linescan.
I also added logging to the methods in the framer that throw an exception because they are not supported.
There is one method that is not tested, `getCrossCovarianceMatrix`, because I am unsure how we are supposed to call it.
> Added tests to check that the framer logs

- include/usgscsm/Distortion.h
- src/Distortion.cpp
Increased max iteration count, loosened precision, and acceptance criteria for Radial Distortion. 
Isis uses pixel pitch as the tolerance, CSM doesn't have access to pixel pitch so just punting it for now.
> updated distortion to closer match ISIS

- include/usgscsm/Distortion.h
- src/Distortion.cpp
- src/Utilities.cpp
- tests/DistortionTests.cpp
This is the distortion model used by both the TC and MI, which are part of the LISM.
The only change from the old Kaguya TC distortion model is accounting for the boresight as indicated in the IKs and Hiro's script.
This is going to require a coordinated change in ALE to provide the updated distortion. I thought about keeping it backwards compatible and setting the boresight values to 0, but I don't want to introduce a situation where the code silently falls back to a less correct solution to support old ISDs.
> Updated Kaguya LISM distortion model

- tests/data/constVelocityLineScan.json
- tests/data/orbitalLineScan.json
This caused the test images to sometimes fail when testing imageToGround -> groundToImage. For example, if testing line 2, sample 8 that ground point could fall on line 1 or 2. If the algorithm picks line 1, it should map to ccd line 1 and then back to image line 2. because the ccd lines were flipped, it instead mapped to ccd line -1 and then back to image line 0.
> Fixed Line Scan test images having lines flipped

- include/usgscsm/UsgsAstroLsSensorModel.h
- include/usgscsm/Utilities.h
- src/UsgsAstroLsSensorModel.cpp
- src/Utilities.cpp
- tests/UtilitiesTests.cpp
The plane methods would be needed for CPPS search instead of the generalized detector distance, but I left them in if we every want CPPS.
> Added methods for computing linearized detector coordinates

- src/UsgsAstroFrameSensorModel.cpp
- src/UsgsAstroLsSensorModel.cpp
- tests/FrameCameraTests.cpp
- tests/LineScanCameraTests.cpp
Adds an inaccurate implementation to get the date and time of a given reference point on an image. This method is inaccurate due to the differences in time computation between NAIF and default timing libraries. Mainly, NAIF accounting for leap seconds in it's timing the the differences between epochs (NAIF: January 1st, 2000 C++: Janurary 1st: 1970)
Closes #250
> Inaccurate Implementation for getReferenceDateAndTime

- include/usgscsm/UsgsAstroPlugin.h
- include/usgscsm/UsgsAstroSarSensorModel.h
- src/UsgsAstroPlugin.cpp
- src/UsgsAstroSarSensorModel.cpp
- tests/PluginTests.cpp
- tests/data/orbitalSar.json
A lot of this is commented out because not all of the virtual methods are implemented for the SAR model yet. Thus, we can't actually instantiate anything without undefined symbol errors. Once everything is implemented, even just as a stub, then the commented code can be un-commented.
> SAR instantiation logic

- include/usgscsm/UsgsAstroSarSensorModel.h
- include/usgscsm/Utilities.h
- src/UsgsAstroSarSensorModel.cpp
- src/Utilities.cpp
- tests/SarTests.cpp
- tests/UtilitiesTests.cpp
This handles most of the math involved in image to ground. There are a few things still missing here:
1. the left/right look is waiting on #283 
1. This only does a sphere
1. The test image result is only accurate to within a handful of millimeters
There are also a handful of nice to have things that aren't in here:
1. ~Proper vector math operators with ecefVectors and ecefCoords~
1. Separate methods that compute the circle of points at the proper range.
> Added most of imageToGround

- include/usgscsm/UsgsAstroFrameSensorModel.h
- include/usgscsm/UsgsAstroLsSensorModel.h
- include/usgscsm/UsgsAstroPlugin.h
- src/UsgsAstroFrameSensorModel.cpp
- src/UsgsAstroLsSensorModel.cpp
- src/UsgsAstroPlugin.cpp
- tests/Fixtures.h
Changes how logging is handled in both the Framer and Line Scanner sensor models. The plugin now handles logger creation and each sensor model will only log if this logger is present.
Whenever a plugin is in instantiated, the plugin will also create a logger called `usgscsm_logger` which will have a sink defined in the environment variable `ALE_LOG_FILE`. The two sensor models write to this logger by default.
If you want to adjust where either of the sensor models write to, you'll need to create a new spd logger, register said logger, and update the name of the logger for the sensor model you are working with. As such this can only really be done on the C++ side but the output location of your log can be changed on the fly by changing `ALE_LOG_FILE`.
A few things to potentially discuss: …
> Logging Update

- include/usgscsm/Utilities.h
- src/UsgsAstroSarSensorModel.cpp
- src/Utilities.cpp
- tests/UtilitiesTests.cpp
The slantRangeToGroundRange function finds the zero of a polynomial using a generic secant method. It's faster and doesn't require bounding the root if we instead use Newton's method.
> Replaced secant root with Newton's method in SAR

- include/usgscsm/Distortion.h
- include/usgscsm/UsgsAstroFrameSensorModel.h
- include/usgscsm/UsgsAstroLsSensorModel.h
- include/usgscsm/UsgsAstroPlugin.h
- include/usgscsm/UsgsAstroSarSensorModel.h
- include/usgscsm/Utilities.h
- src/Distortion.cpp
- src/UsgsAstroFrameSensorModel.cpp
- src/UsgsAstroLsSensorModel.cpp
- src/UsgsAstroPlugin.cpp
- src/UsgsAstroSarSensorModel.cpp
- src/Utilities.cpp
- tests/DistortionTests.cpp
- tests/Fixtures.h
- tests/FrameCameraTests.cpp
- tests/ISDParsingTests.cpp
- tests/LineScanCameraTests.cpp
- tests/PluginTests.cpp
- tests/SarTests.cpp
- tests/TestMain.cpp
- tests/UtilitiesTests.cpp
This PR contains the result of running just `clang-format style=Google` on the usgscsm code. This standardizes spacing, bracket-placement, header-ordering, max line length, etc, but doesn't contain changes resulting from static analysis and `cpplint` does still find some additional changes that need to be made by hand. (I'm not sure if these additional changes should be in _this_ PR or a subsequent one. I was leaning toward a subsequent one just so the automated changes and hand-changes could be in separate PRs. The changes left to be made are a much smaller list than the changes in this PR.)
I tested a few formats, and picked Google style because I somewhat arbitrarily liked the way the results looked the best. I have results locally for the following formats if anyone would like to see …
> Updated to use Google style for formatting

- include/usgscsm/UsgsAstroLsSensorModel.h
- src/UsgsAstroFrameSensorModel.cpp
- src/UsgsAstroLsSensorModel.cpp
- src/UsgsAstroPlugin.cpp
- src/UsgsAstroSarSensorModel.cpp
Also fixed a focalPlaneY that should have been a focalPlaneX.
Also fixes logging file environment variable name #299.
> Removed unused code identified by clang-tidy and me

- src/UsgsAstroFrameSensorModel.cpp
- src/UsgsAstroLsSensorModel.cpp
- tests/FrameCameraTests.cpp
The linescan and framing models errored when you accessed their parameter sharing criteria. This is not what's suppose to happen when parameters are not sharable. Instead, they should return the default SharingCriteria.
This was causing the default GeometricModel::getParameter and GeometricModel::getParameters to raise an exception when they shouldn't.
> Added no sharing criteria

- src/UsgsAstroFrameSensorModel.cpp
- src/UsgsAstroLsSensorModel.cpp
- src/UsgsAstroSarSensorModel.cpp
- tests/FrameCameraTests.cpp
- tests/LineScanCameraTests.cpp
- tests/SarTests.cpp
Updates all sensor models provided by usgscsm to use ISO8601 for times output by `getReferenceDateAndTime()`, as required by the CSM specification. 
This fixes #320.
> Update getReferenceDateAndTime() to follow ISO8601

- include/usgscsm/Utilities.h
- src/UsgsAstroFrameSensorModel.cpp
- src/UsgsAstroLsSensorModel.cpp
- src/UsgsAstroPlugin.cpp
- src/UsgsAstroSarSensorModel.cpp
- src/Utilities.cpp
- tests/Fixtures.h
- tests/FrameCameraTests.cpp
- tests/LineScanCameraTests.cpp
- tests/UtilitiesTests.cpp
Fixes #317 by adding the sensor model name to the beginning of the state string for all sensor models. This change is backwards compatible, so existing state strings without the model name still work. Work done with @scsides.
> Updated state string to begin with the sensor model name as per the CSM standard

- src/UsgsAstroFrameSensorModel.cpp
- src/UsgsAstroLsSensorModel.cpp
Fixes #324 
I updated ALE to the version with the proper fix in the submodule and added a work-around for situations where an external ALE build is used and doesn't have the fix.
I am not super happy with the work-around but I tested a bunch of ISDs for frames and linescanners with their angular velocities removed and it worked as expected.
> Fixed seg fault when using an ISD without angular velocities

- README.md
- environment.yml
This repo does not compile with cmake 3.10 because its "ale" dependency, which is included as a submodule, needs cmake 3.15.
Also, the "conda create" command fails with the "-y" flag. This is confirmed by the doc of this command, where the "-y" flag is not present: 
https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands
> Bump up cmake requirement to 3.15 and fix the conda env command

- include/usgscsm/UsgsAstroLsSensorModel.h
- include/usgscsm/Utilities.h
- src/UsgsAstroLsSensorModel.cpp
- src/Utilities.cpp
- tests/LineScanCameraTests.cpp
This makes it possible to apply to a linescan model state a rotation and translation, whose effect is to change the camera position and orientation in ECEF.
This is something I needed in ASP for bundle adjustment. I have a copy of this functionality over there, so I don't need this pull request for my own work, but I thought it would make sense in the linesecan model and could be used by other tools which need to modify this state.
> Add the ability to apply a transform to a linescan model

- include/usgscsm/UsgsAstroLsSensorModel.h
- src/UsgsAstroLsSensorModel.cpp
This is a fix for the situation when the linescan sensor groundToImage() function fails to converge to desired precision. The problem is that sometimes the step size being used is too big, and it overshoots. The solution is to make the step size smaller when this scenario is detected.
This situation is supposed to happen only for some peculiar sensors. I ran into it with LRO NAC towards the South Pole, as described here: https://github.com/USGS-Astrogeology/usgscsm/issues/357
In situations where things were fine even before, I verified that no changes will happen.
It is not clear how much smaller to try to make the step. Here I chose to make it half the original size when the original one is too big. Presumably, the closer one is to the "optimal" size, the faster the algorithm will …
> Fix for the linescan sensor, the step size can be too big when iterating

- src/Utilities.cpp
- tests/SarTests.cpp
I found a bug in the brentRoot() code for finding a root of a function. This was preventing the SAR groundToImage() function from converging on occasion.
This root-finding algorithm starts with function values of opposite signs at the ends of an interval, then narrows down the interval while still keeping function values of opposite sign, till the interval is below tolerance length, then it declares to have found the solution.  
If however the algorithm runs into a position where the function value is precisely 0, it can't believe its luck, and keeps on going through the motions, while returning a poor value for the root.
Per Wikipedia, https://en.wikipedia.org/wiki/Brent%27s_method, there must be an additional check for this, which is missing. I put it in. 
To reproduce that the current …
> Brent root fix

- src/UsgsAstroSarSensorModel.cpp
- tests/SarTests.cpp
This is a fix for the fact that imageToRemoteImagingLocus() was giving an incorrect answer (https://github.com/USGS-Astrogeology/usgscsm/issues/350). 
The problem seems to be that this function goes through some of the same motions as imageToGround() (with different notation), but returns the cross-track vector instead of the vector pointing to the ground.
I could have just pasted the same logic as in imageToGround(), or carefully adjusted the existing  imageToRemoteImagingLocus() code along the same lines, but that would have been just code repetition. So, the change I made is to call the correct function imageToGround() and then finish the rest of the calcuation. I used a height of 0 when calling this, since we don't care to hit a specific height above datum, we just want the direction …
> Bugfix in imageToRemoteImagingLocus

- src/UsgsAstroSarSensorModel.cpp
- tests/SarTests.cpp
This is a fix for https://github.com/USGS-Astrogeology/usgscsm/issues/349. The ISIS and CSM SAR models were disagreeing by 0.5 pixels.
To verify that the problem still exists, I upgraded to ISIS 6.0.0, set ISISROOT and PATH to reflect this version, then ran the script vis.py from knoten. Here were the stats printed before:
isis2csm_data
diff line  diff sample
count  100.000000   100.000000
mean     0.000653     0.500945
std      0.000364     0.000868
min      0.000088     0.499861
25%      0.000334     0.500069
50%      0.000661     0.500880
75%      0.000985     0.501837
max      0.001184     0.502175
csm2isis_data
diff line  diff sample
count  100.000000   100.000000
mean    -0.000587    -0.499855
std      0.000331     0.003402
min     -0.000953    -0.502177
25%     -0.000923 …
> Fix for 0.5 pixel shift in the SAR model

- .gitignore
- CMakeLists.txt
- bin/usgscsm_cam_test.cc
- tests/CMakeLists.txt
This is a tool intended to be shipped with the usgscsm library (it will install itself in 'bin'). The goal is for the user to invoke it for basic sanity checks of CSM models. For now, all it can do is load a CSM model, for example, as:
bin/usgscsm_cam_test tests/data/orbitalSar.json 
when it will produce output:
Loaded CSM model of type USGS_ASTRO_SAR_SENSOR_MODEL from ../tests/data/orbitalSar.json.
Future proposed functionality:
- Test projecting rays from the camera to ground and vice-versa, with given sample rate.
- Load a CSM model state (stored in a .json file, just like an ISD model).
- Ability to export a CSM model in ISD format to a CSM model state file.
> Add the tool usgscsm_cam_test

- bin/usgscsm_cam_test.cc
I added some simple parsing which assumes each option has only one value. We could incorporate getopt.h into the code but that one is GPL, which can be problematic. This seems to work. Let's see how the windows build is working out.
> Remove the dependency on getopt.h

- src/UsgsAstroFrameSensorModel.cpp
- src/UsgsAstroLsSensorModel.cpp
- src/UsgsAstroPlugin.cpp
- src/UsgsAstroPushFrameSensorModel.cpp
- src/UsgsAstroSarSensorModel.cpp
- tests/Fixtures.h
- tests/FrameCameraTests.cpp
- tests/PluginTests.cpp
This replaces some bare pointers with smart pointers where the API allows for it. This is less error-prone. In fact, I think I found a little bug here: 
https://github.com/oleg-alexandrov/usgscsm/commit/4a99a074204a946be7d71cde55c7b2fd412752d0#diff-f900e8fad537ea95223efd435687144ea33ba3ee546fab412522f91e74fdc61fL130
where a pointer was first assigned to null and then deleted, which would mean the memory was actually not deallocated.
> Avoid using pointers where a std::shared_ptr can be used

- include/usgscsm/UsgsAstroLsSensorModel.h
- src/UsgsAstroLsSensorModel.cpp
I made a 23% speed improvement in the linescan sensor logic, without changing the results. This relies on avoiding computing the interpolated velocity and applying adjustments when those are not used by the caller.
To verify this, run:
cd usgscsm/build
time ./usgscsm_cam_test --model ../tests/data/toughLroNacLineScan.json --sample-rate 1
before and after applying the fix. On my machine the run time is 155 seconds before the fix, and 118 seconds after it. Granted, not a huge improvement, but it is notable, and the code changes are small.
> Speedup in Linescan model by avoiding unneeded computations

- CMakeLists.txt
- environment.yml
- include/usgscsm/EigenUtilities.h
- include/usgscsm/UsgsAstroLsSensorModel.h
- src/EigenUtilities.cpp
- src/UsgsAstroLsSensorModel.cpp
- tests/CMakeLists.txt
- tests/EigenUtilitiesTests.cpp
I implemented an initial guess ground-to-image function for the linecan model which is a projective transform, instead of the existing linear transform. The hope is that this makes more sense geometrically when it comes to projections into camera, so it would fit better the function we want. It is also not that nonlinear to be concerned about it doing funny things when out of range.
With the difficult LRO NAC dataset from the repo, the guessed line using this initial guess projective transform differs from the
eventual computed value of this line by 0.69 pixels.  Before, with the linear approximation, the discrepancy was 82.7 pixels.
With a CTX dataset, the mean line error was 160.4 pixels before, and is 0.85 pixels now.
This does not in a dramatic speed improvement though, because the …
> Add an initial projective approximation for linescan camera

- include/usgscsm/UsgsAstroPushFrameSensorModel.h
- src/UsgsAstroPushFrameSensorModel.cpp
The old code was doing a binary search using the sensor distance. This worked when the observation was perfectly nadir, but when the observation is off-nadir, we want to instead find the frame where the ground point is observed closest to the center of the frame.
> Updated push frame to use secant frame search

- include/usgscsm/UsgsAstroFrameSensorModel.h
- include/usgscsm/UsgsAstroSarSensorModel.h
- src/UsgsAstroFrameSensorModel.cpp
- src/UsgsAstroLsSensorModel.cpp
- src/UsgsAstroSarSensorModel.cpp
- src/Utilities.cpp
- tests/FrameCameraTests.cpp
- tests/SarTests.cpp
I added functions to apply a transform to model state for SAR and Frame sensors (such logic for Linescan sensors was added a while ago). I put unit tests too. 
There are some other very small fixes, including to dump in some more places the model state on multiple lines. 
I made the function getModelNameFromModelState() in the Sar class static as in the rest of the the classes, which required removing some debug lines, which is not likely to affect anything. 
I don't need these functions for ASP, as for now I use a clone of these, but when a new USGSCSM version is pushed to conda, I will use the functions from here instead of the ones in ASP.
These changes were tested very carefully with real data, though the unit test provided here is a trivial one to just go through the motions.
> Add functions for applying transform to SAR and Frame sensor

- bin/usgscsm_cam_test.cc
- include/usgscsm/Utilities.h
- src/Utilities.cpp
Related to #400 
To close the issue, we just need to add test data and a unit test!
```
./usgscsm_cam_test --model ESP_037330_1990_REDmos_hijitreged.preTriang.sup --output-model-state ESP_out.json
Detected CSM plugin: UsgsAstroPluginCSM
Number of models for this plugin: 4
Loaded a CSM model of type USGS_ASTRO_LINE_SCANNER_SENSOR_MODEL from model state file ESP_037330_1990_REDmos_hijitreged.preTriang.sup.
Writing model state: ~/gxp/ESP_out.json
```
> Added string sanitize function

- bin/usgscsm_cam_test.cc
- docs/source/tools/usgscsm_cam_test.rst
- src/Utilities.cpp
- tests/UtilitiesTests.cpp
Adds optional parameter for running `usgscsm_cam_test` with a .sup file to modify camera state within .sup file with new model inputted with `--model` parameter.
Updates documentation and tests associated with usgscsm_cam_test.
> Adds ability to modify GXP .sup Camera State using usgscsm_cam_test

- include/usgscsm/UsgsAstroFrameSensorModel.h
- include/usgscsm/Utilities.h
- src/UsgsAstroFrameSensorModel.cpp
- src/Utilities.cpp
- tests/Fixtures.h
- tests/FrameCameraTests.cpp
- tests/UtilitiesTests.cpp
- tests/data/jitterFramer.json
Adds initial rolling shutter frame jitter support to the frame sensor model. An accompanying PR will be in ALE to add this to the ISD for EIS NAC/WAC FC imagery.
> Initial frame jitter

- src/UsgsAstroLsSensorModel.cpp
The change in #385 only checks for adjustments being passed into the function, it doesn't check for adjustments that already exist in the model.
This resulted in the velocity not being computed when adjustments were set in the model and then it cannot compute the in-track.cross-track coordinate system properly.
> Checked for set adjustments in getAdjSensorPosVel when determining if velocity is needed

- CMakeLists.txt
- include/usgscsm/UsgsAstroPlugin.h
- src/UsgsAstroFrameSensorModel.cpp
- src/UsgsAstroPlugin.cpp
Both CSM and ISIS have a header file named Plugin.h, which can result in a compile-time error for code which includes both. This proposes a fix by disambiguating some csm headers by replacing "Plugin.h" with "csm/Plugin.h", etc.
> Fix compile-time conflict due to ambiguous Plugin.h

- src/UsgsAstroPushFrameSensorModel.cpp
- src/Utilities.cpp
Somehow the PushFrame sensor model is missing a minor bit of logic present for the other models (Frame, Linescan SAR). When a transform is applied to the cameras, the ground reference point should move accordingly, as the camera centers (and orientations and velocities) move. 
Likely this does not matter much, if at all, as the reference point is only used to set up m_gsd and other such things when the model state is created, and it is not used later during actual image-to-ground and ground-to-image operations, but likely it is best to keep it consistent with the rest of the model.
> Apply transform to reference point in PushFrameSensor and spellcheck

- src/UsgsAstroLsSensorModel.cpp
This is a housekeeping fix. The variable m_startingDetectorLine was not being initialized during the reset() call. Normally that's not an issue if the linescan model is being read from an isd, but may be an issue if it is created from scratch. Now this is also going to be consistent with  m_startingDetectorSample (line right above).
> Initialize m_startingDetectorLine

- src/UsgsAstroFrameSensorModel.cpp
- src/UsgsAstroLsSensorModel.cpp
When converging on an approximate line, when calculating for the error in the detector distortion was not being applied.
On cameras with fairly minor distortion this results in fairly minimal difference in resulting line. On camers, like kaguyatc, with more prevalent distortion, this caused the line to be off by as much as 2 pixels.
Related to this ALE issue: https://github.com/USGS-Astrogeology/ale/issues/508
> Line Scan groundToImage Fix

- src/UsgsAstroProjectedSensorModel.cpp
- src/Utilities.cpp
- tests/PluginTests.cpp
- tests/UtilitiesTests.cpp
A known .5 pixel offset exists between ISIS and CSM. This was being handled inside of the projected camera model, and should now be handled externally by the user if they are comparing ISIS and CSM
> Small Projected Camera Fix

- include/usgscsm/UsgsAstroFrameSensorModel.h
The FrameSensor class has its members private, but has no set or get functions so those cannot be accessed. This is a proposal to make them public, as done already for the Linescan class. (A few members will still be kept private, which are internal states, such as the logger and the _state variable). 
I care primarily for the intrinsics (distortion, focal length), camera position, and camera orientation, as those are needed in bundle adjustment. But I don't think there's harm in having other class parameters be public, such as semi-major axis, semi-minor axis, etc. 
Thoughts?
> FrameSensor: Make many members public so they can be changed

- src/Distortion.cpp
- tests/DistortionTests.cpp
This is a proposed fix to https://github.com/DOI-USGS/usgscsm/issues/461.
The issue here is that with the unmodified code the radial distortion and undistortion operations are not being applied when the pixel value is very close to the origin. 
Ironically, this is when distortion and undistortion is most likely to converge well, as, radial distortion this is just some multiplications and additions. Radial undistortion is about the same thing.
There is no division by a number close to zero anywhere where one should need to ensure a tolerance must be respected.
I modified the unit test to make it more realistic, by using non-zero distortion coefficients. Before the proposed fix, the test will fail, as distortion and undistortion are not true inverse of each other. That is because, before …
> No need for tolerance check for radial distortion

- include/usgscsm/Distortion.h
- include/usgscsm/Utilities.h
- src/Distortion.cpp
- src/Utilities.cpp
- tests/CMakeLists.txt
- tests/DistortionTests.cpp
- tests/Fixtures.h
- tests/data/dawnfc_radtan.json
Add support for the radial + tangential distortion model. This has 5 distortion coefficients, stored in order k1, k2, p1, p2, k3. The k1, k2, k3 coefficients are for radial distortion, and p1 and p2 for tangential distortion. This was validated with the OpenCV implementation using the function cv::projectPoints().
Corresponding code was added in "ale" (https://github.com/DOI-USGS/ale/pull/575). 
The issue discussing this: https://github.com/DOI-USGS/usgscsm/issues/465
Tests were added for:
- Ensuring distortion and undistortion are inverse to each other
- Loading an ISD and running image-to-ground and ground-to-image operations, and saving a state file. The ISD was obtained from a DawnFC example by replacing the DawnFC distortion (which is only radial with one coefficient) by the larger …
> Support for the radial + tangential distortion model

- CHANGELOG.md
- CMakeLists.txt
- code.json
- recipe/meta.yaml
Updates USGSCSM for a 2.0.1 release. Does not touch the meta.yaml as the builds come from the conda-forge feedstock.
> 2.0.1 prep

- LICENSE.md
This is a simple typo fix in the LICENSE.md file where BDS 3 was mistakenly put instead of BSD 3; closes #450.
> license typo fix: BDS 3 -> BSD 3

- CMakeLists.txt
Fixed json headers being installed along side usgscsm and potentially overwriting other json installs
> Json Header Install Fix

- .github/workflows/ci_testing.yml
Updates the checkout action to the 4.0.0 commit. 
Updates the conda env build action to 3.0.0 commit.
Updates the artifact upload to 4.0.0 commit.
All updates fix deprecation warnings for the actions, updating them to use Node.js 20 rather than Node.js 19. 
> Update checkout action

- src/UsgsAstroLsSensorModel.cpp
When a CSM linescan model is loaded, some auxiliary info is computed, including the GSD, reference point, and flying height. 
All but the last one use the image center (half image dimensions) for the computations. But the flying height uses time 0. Time 0 is not well-defined for a linescan sensor. One should use either the starting time as set in the metadata, or the time at starting line, or some time that is relevant to the given sensor.
I ran into this when creating custom linescan models. The resulting flying height then ends up being quite off, depending on what the starting time is.
The proposed fix uses the image center time to find the flying height, for consistency with GSD and reference point calculations.
The effect of this fix in practice is very small, unless one does unusual …
> Use image center when computing flying height

- include/usgscsm/Distortion.h
- src/Distortion.cpp
- src/UsgsAstroFrameSensorModel.cpp
- src/UsgsAstroLsSensorModel.cpp
- src/UsgsAstroPushFrameSensorModel.cpp
- tests/DistortionTests.cpp
The OpenCV radial-tangential distortion model I added a few months ago is useful on the ASP side and helps with combining data from multiple vendors (and sensor types) under the CSM umbrella.
I found there is a bug, however, in my implementation, that is due to insufficiently clear OpenCV documentation regarding lens distortion at: https://docs.opencv.org/4.x/dc/dbb/tutorial_py_calibration.html
That does not say that distorted and undistorted pixels must be normalized by focal length. I found this bit by looking at another doc page, at https://docs.opencv.org/4.x/d9/d0c/group__calib3d.html
I put a fix and validated that this agrees with OpenCV's implementation. Before, I had tested only the distortion/undistortion formula, rather than the full chain of world-to-pixel transform, that's why …
> Fix for radial-tangential distortion

- CHANGELOG.md
- src/Distortion.cpp
> Cahvor fix

- CMakeLists.txt
This is a fix for the usgscsm_cam_test tool not being able to find libusgscsm, once it is installed in lib/csmplugins.
This was tested for Mac and Linux.
Also, on line 124 in CmakeLists.txt there was a Unicode whitespace that renders in binary in some editors, so I replaced with a plain whitespace.
> Ensure usgscsm_cam_test can find libusgscsm

- CHANGELOG.md
- include/usgscsm/UsgsAstroFrameSensorModel.h
- src/UsgsAstroFrameSensorModel.cpp
- tests/FrameCameraTests.cpp
- Removed any checks at all for pixel boundary in UsgsAstroFrameSensorModel::getSensorPosition(imageCoord).
- Added a test to check a pixel exceeding the boundary.
Fixes #489 
> Frame cam no bounds

- CHANGELOG.md
- src/UsgsAstroFrameSensorModel.cpp
The value of ephemeris time is in double precision, both in ISIS, ALE, and in USGSCSM, except for this one place, where it is cast to int. The effect is that a timestamp is saved as:
"m_ephemerisTime": 717716358.0,
instead of a correct value such as:
"m_ephemerisTime": 717716358.2862071,
> m_ephemerisTime should be double
