DOI-USGS/usgscsm

.travis.yml, CMakeLists.txt, recipe/build.sh, recipe/meta.yaml, tests/TestyMcTestFace.cpp
To discuss: with how cmake is building our shared library, the conda build also includes the libcsmapi.so is that what we want?
=> Adds conda deploy via travis

tests/CMakeLists.txt, tests/TestyMcTestFace.cpp, tests/data/simpleFramerISD.json
This is not exhaustive but it's a start.
=> Improved frame plugin testing

tests/CMakeLists.txt, tests/FrameCameraTests.cpp, tests/TestMain.cpp, tests/data/simpleFramerISD.json
=> Test camera model

.travis.yml, src/UsgsAstroFramePlugin.cpp, src/UsgsAstroFrameSensorModel.cpp, tests/data/simpleFramerISD.json
One last edit, noticed the last test failed due to a segfault, in hastily scanning the plugin member vars for things that should be 0 I accidentally passed 0.0 to std::vecotor::assign which should be a 10, essentially creating a 0 element vector.
=> patched segfault error + added detector center as defined in json schema

include/usgscsm/UsgsAstroFrameSensorModel.h, jupyter_notebooks/CameraTesting_img2ground_distortion_v1.ipynb, jupyter_notebooks/UsgsAstroFrameSensorModelTesting.ipynb, src/UsgsAstroFrameSensorModel.cpp, tests/FrameCameraTests.cpp, tests/data/simpleFramerISD.json
I also added the ability to test protected/private member functions in classes using the FRIEND_TEST macro in gtest (although I am not happy with this particular implementation).
Additionally in the test fixture, I load the ISD and replace the odt_x,odt_y vectors with those defined within
the ik kernel for the MDIS NAC.  I did this through the ISD.  There might be a better way to do it
through the nlohmann::json api though.
=> Added framing test for setFocalPlane.  

README.md
=> Added ISD spec to README

.gitignore, src/UsgsAstroLsSensorModel.cpp
=> Added a check for impossible samples in ground to image

src/UsgsAstroFramePlugin.cpp, src/UsgsAstroFrameSensorModel.cpp, tests/FrameCameraTests.cpp, tests/data/simpleFramerISD.json
This gets all of the current tests in this branch passing.
=> Fixed optical distortion and pixel to focal transforms.

src/UsgsAstroLsSensorModel.cpp
This error also needs to be changed to a warning based on #107
=> changed groundtoimage out of image error to warning.

.travis.yml
=> Adds in check for PR for upload

.appveyor.yml, CMakeLists.txt, src/UsgsAstroLsPlugin.cpp, src/UsgsAstroLsSensorModel.cpp, src/UsgsAstroLsStateData.cpp, tests/CMakeLists.txt
Going to close the other PR to try and get a clean set of commits.
=> Windows Build

include/usgscsm/UsgsAstroLsSensorModel.h, src/UsgsAstroLsSensorModel.cpp, tests/CMakeLists.txt, tests/Fixtures.h, tests/LineScanCameraTests.cpp, tests/data/constVelocityLineScan.json
This also adds a very simple test to the line scan camera and some test stubs.
=> Fixed ground to image and image to ground not giving inverse results.

src/UsgsAstroLsSensorModel.cpp
=> Added debug output to ground to image error message.

CMakeLists.txt, include/usgscsm/Distortion.h, include/usgscsm/UsgsAstroFrameSensorModel.h, include/usgscsm/UsgsAstroLsSensorModel.h, src/Distortion.cpp, src/UsgsAstroFrameSensorModel.cpp, src/UsgsAstroLsSensorModel.cpp, tests/CMakeLists.txt, tests/DistortionTests.cpp, tests/Fixtures.h, tests/FrameCameraTests.cpp
Extracts distortion models from the Line Scanner and Framer cameras into it's own function set. Closes #167
=> Distortion

src/UsgsAstroLsSensorModel.cpp
This code should be cleaned up between the framer and LS see #176 
This PR is continued work on #163 attempting to get GXP to work.
=> Copied unit conversion from framer to ls

src/UsgsAstroLsSensorModel.cpp, src/UsgsAstroPlugin.cpp, tests/LineScanCameraTests.cpp, tests/PluginTests.cpp
I chose to make the value just a flat array because that better lines up with how we are handling arrays in the state.
=> Fixed state being written out and read in differently

tests/UtilitiesTests.cpp
This is a follow on for #186 to get tests passing
=> Fixed computeDistortedFocalPlaneCoordinates test

src/Utilities.cpp, tests/LineScanCameraTests.cpp
=> Fixed some docs

src/UsgsAstroLsSensorModel.cpp, tests/LineScanCameraTests.cpp
=> Fixed imageToRemoteImagingLocus in LS and a bug with quaternions

src/UsgsAstroLsSensorModel.cpp
=> Removes #define

src/UsgsAstroFrameSensorModel.cpp
=> Changed frame covariance to identity

src/UsgsAstroFrameSensorModel.cpp
Updated reference point to the center of the image
=> Framer Fix

src/UsgsAstroFrameSensorModel.cpp, tests/FrameCameraTests.cpp
Updated framer test to reflect the change in the reference point computation
=> Framer Test Fix

include/usgscsm/UsgsAstroFrameSensorModel.h, src/UsgsAstroFrameSensorModel.cpp, tests/FrameCameraTests.cpp
=> Made framer inherit from settable ellipsoid

include/usgscsm/Distortion.h, src/Distortion.cpp, src/UsgsAstroFrameSensorModel.cpp, src/UsgsAstroLsSensorModel.cpp, src/Utilities.cpp, tests/DistortionTests.cpp
Adds the dawn distortion model and fixes the line scanners warning system to properly propagate warnings back to the user. Closes #230
=> Dawn Distortion

src/UsgsAstroFrameSensorModel.cpp
This is for testing on GXP right now. Do not merge.
=> Normalized quaternion in framer

src/UsgsAstroLsSensorModel.cpp, tests/DistortionTests.cpp
Adds tests for the dawn and kaguya distortion models.
=> Distortion Model Testing

src/UsgsAstroLsSensorModel.cpp
When I try to compile this code I get an error about an ambigous isnan() function. It works when I use std::isnan() which is perhaps what is needed.
=> Fix compile error

src/UsgsAstroLsSensorModel.cpp, src/UsgsAstroPlugin.cpp, src/Utilities.cpp
This work supports Kaguya MI as it uses the same model as Kaguya TC, except it has 3 coefficients instead of 4.
=> Improved error reporting and fixed a bug with the kaguyatc distortion model

CMakeLists.txt
Superfluous change to tick version but I figure it might as well get done.
=> version tick to 1.4.0

src/UsgsAstroLsSensorModel.cpp
=> Removed warning when log_file missing in LS

include/usgscsm/UsgsAstroLsSensorModel.h, include/usgscsm/Utilities.h, src/UsgsAstroLsSensorModel.cpp, src/Utilities.cpp, tests/UtilitiesTests.cpp
=> Merge distance and linearization into dev

include/usgscsm/UsgsAstroLsSensorModel.h, src/UsgsAstroLsSensorModel.cpp, tests/Fixtures.h, tests/data/orbitalLineScan.json
Reverts USGS-Astrogeology/usgscsm#268
=> Revert "Added check for downtrack line direction"

include/usgscsm/UsgsAstroLsSensorModel.h, src/UsgsAstroLsSensorModel.cpp, tests/LineScanCameraTests.cpp, tests/data/constVelocityLineScan.json, tests/data/orbitalLineScan.json
Updates imageToGround to use values read from the isd and converts the detector line to image line
=> ImageToGround and groundToImage changes

src/UsgsAstroLsSensorModel.cpp, tests/Fixtures.h, tests/LineScanCameraTests.cpp
=> Implemented cross covariance method

include/usgscsm/Utilities.h, src/Utilities.cpp, tests/UtilitiesTests.cpp
This adds Brent's root finding algorithm which we will need to compute the 0 doppler shift time and the ground range in the SAR groundToImage method.
=> Added root finding algorithm

CMakeLists.txt, include/usgscsm/UsgsAstroSarSensorModel.h, src/UsgsAstroSarSensorModel.cpp, tests/SarTests.cpp
Added a bunch more methods. Most of this is copy and paste from the line scanner.
=> More stubs

include/usgscsm/UsgsAstroLsSensorModel.h, include/usgscsm/UsgsAstroSarSensorModel.h, include/usgscsm/Utilities.h, src/UsgsAstroLsSensorModel.cpp, src/UsgsAstroSarSensorModel.cpp, src/Utilities.cpp, tests/SarTests.cpp
Added both imaging loci functions, ellipsoid intersection in image to ground, and look direction in image to ground.
=> Adds SAR imaging loci functions and fixes imagetoground

include/usgscsm/UsgsAstroLsSensorModel.h, include/usgscsm/UsgsAstroPlugin.h, include/usgscsm/Utilities.h, src/UsgsAstroFrameSensorModel.cpp, src/UsgsAstroLsSensorModel.cpp, src/Utilities.cpp
This trims out the use of the ISD object and means we don't need as many changes in ALE for this to work.
=> Direct isd parsing

include/usgscsm/UsgsAstroFrameSensorModel.h, include/usgscsm/UsgsAstroLsSensorModel.h, include/usgscsm/UsgsAstroPlugin.h, src/UsgsAstroFrameSensorModel.cpp, src/UsgsAstroLsSensorModel.cpp, src/UsgsAstroPlugin.cpp, tests/Fixtures.h
Reverts USGS-Astrogeology/usgscsm#293
=> Revert "Merge dev into ale_update branch"

README.md, include/usgscsm/Distortion.h, include/usgscsm/UsgsAstroFrameSensorModel.h, include/usgscsm/UsgsAstroLsSensorModel.h, include/usgscsm/UsgsAstroPlugin.h, include/usgscsm/Utilities.h, src/UsgsAstroFrameSensorModel.cpp, src/UsgsAstroLsSensorModel.cpp, src/UsgsAstroPlugin.cpp, src/Utilities.cpp
This PR excludes changes to SAR so that they don't conflict with the work that @jessemapel is doing on #310
=> More linter-suggested formatting changes, warnings added for non-intersection, and clean up duplicate code

CMakeLists.txt, README.md, include/usgscsm/UsgsAstroPlugin.h, src/UsgsAstroPlugin.cpp
Also updated the README with more up to date information and how to enable logging.
=> Added the ability to log to standard out and standard error

src/UsgsAstroFrameSensorModel.cpp, src/UsgsAstroLsSensorModel.cpp, src/UsgsAstroSarSensorModel.cpp, tests/FrameCameraTests.cpp, tests/LineScanCameraTests.cpp, tests/SarTests.cpp
=> Added precision setting in locus methods, no linting

src/UsgsAstroPlugin.cpp
Added a handful of deletes so that we aren't just making models and moving on.
Fixes #316
=> Fixed memory leaks in Plugin methods

.github/workflows/ci_testing.yml
Continuation of #345 now that we have GH actions in the repo.
Fixes #342
=> Getting GH actions working

src/UsgsAstroFrameSensorModel.cpp, src/UsgsAstroLsSensorModel.cpp, src/Utilities.cpp
=> Added indent and new line to state dumps

CMakeLists.txt
Updates the package version for the 1.6.0 release. As we added new functionality to apply transformations to the LS model this is a new feature release.
=> 1.6.0 version tick

src/UsgsAstroPlugin.cpp
This is a proposed fix for https://github.com/USGS-Astrogeology/usgscsm/issues/375.
=> Check if the loaded model type is what is expected

include/usgscsm/UsgsAstroPushFrameSensorModel.h, src/UsgsAstroPushFrameSensorModel.cpp
Also removed old sensor distance function.
=> Clipped push frame search to within the image

docs/source/sensors/Cassini.rst, docs/source/sensors/Dawn.rst, docs/source/sensors/Galileo.rst, docs/source/sensors/Hayabusa.rst, docs/source/sensors/Juno.rst, docs/source/sensors/LunarReconnaissanceOrbiter.rst, docs/source/sensors/MarsExpress.rst, docs/source/sensors/MarsReconnaissanceOrbiter.rst, docs/source/sensors/Messenger.rst, docs/source/sensors/NewHorizons.rst, docs/source/sensors/Odyssey.rst, docs/source/sensors/Selene.rst, docs/source/sensors/TraceGasOrbiter.rst, docs/source/sensors/Viking.rst, docs/source/sensors/Voyager.rst, docs/source/user/creating_an_environment.rst, docs/source/user/isd_generation.rst
Partially addresses #386
As it stands, this documentation includes:
1. instructions for generating and validating an ISD, including how to handle situations in which ale doesn't find a kernel set, i.e. getting kernels from a spiceinit'd cub
2. processing instructions for WAC
3. a (very) brief summary of each sensor for which ALE drivers exist.  These could use additional information, but I wasn't sure what information was desirable in this context
4. a few processing examples.  I'd like to get an example for each supported driver.  I'm running through knoten + other examples, but I'm going through the process of making sure they actually work + trying to sniff out code rot.
=> Initial user and instrument docs.

README.md, src/UsgsAstroFrameSensorModel.cpp, src/UsgsAstroLsSensorModel.cpp, src/UsgsAstroPlugin.cpp, tests/Fixtures.h
Adds log levels so that we can get better ideas of what's going on at a high level.
See the updated README for how to use this.
Fixes #301
=> Added log levels

.github/workflows/ci_testing.yml, environment.yml, include/usgscsm/Distortion.h, src/Distortion.cpp, src/UsgsAstroFrameSensorModel.cpp, src/Utilities.cpp, tests/DistortionTests.cpp, tests/Fixtures.h
Adds the ability to apply and remove cahvor distortion from our CSM models
=> Cahvor Distortion

CMakeLists.txt, code.json
Updates the version build in cmakelist.txt and adds a new entry into the code.json
=> USGSCSM 1.7.0 release prep

.github/workflows/aws_doc_deploy.yml, .github/workflows/ci_testing.yml, .github/workflows/doc_build.yml
Separates the doc build workflow from the ci workflow for cleaner workflow dependencies
=> Separate Doc workflow

.github/workflows/ci_testing.yml, .gitmodules, CMakeLists.txt
Had to turn off `USGSCSM_EXTERNAL_DEPS` during build and ALE docs build in ci_testing.yml .
=> Update ale submodule

CHANGELOG.md, CMakeLists.txt, code.json
Updated code.json, CMakeLists.txt, and CHANGELOG.md for 2.0.0 release
=> USGSCSM 2.0.0 Release Prep

src/UsgsAstroLsSensorModel.cpp, src/UsgsAstroPushFrameSensorModel.cpp
Partially addresses [Docs issue #51](https://github.com/DOI-USGS/asc-public-docs/issues/51).
=> Added inline descriptions of sensor parameters

environment.yml
=> conda-forge channel only, 3.15 < cmake < 4
